# Generated by Django 3.2.22 on 2023-10-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('about', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=40)),
                ('regular_choice', models.IntegerField(choices=[(1, 'Плацкарт'), (2, 'Купе'), (3, 'СВ'), (4, 'Люкс')])),
                ('smoking_attitude', models.IntegerField(choices=[(1, 'Крайне негативно'), (2, 'Негативно'), (3, 'Нейтрально'), (4, 'Положительно'), (5, 'Крайне положительно')])),
                ('having_children', models.BooleanField()),
                ('sociability', models.IntegerField(choices=[(1, 'Предпочитаю не общаться в поездке'), (2, 'Редко общаюсь'), (3, 'По-разному'), (4, 'Часто общаюсь'), (5, 'Люблю заводить новые знакомства в поездах')])),
                ('pets_attitude', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('seat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('place1', models.CharField(max_length=30)),
                ('place2', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VanCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Плацкарт'), (2, 'Купе'), (3, 'СВ'), (4, 'Люкс')])),
                ('class_van', models.IntegerField(choices=[(1, '3Б'), (2, '3Э'), (3, '2Т'), (4, '2Э'), (5, '1Э'), (6, '1Т'), (7, '1М')])),
                ('seat_quantity', models.IntegerField()),
                ('food', models.BooleanField()),
                ('info_entertaiment', models.BooleanField()),
                ('linen', models.BooleanField()),
                ('biotoilet', models.BooleanField()),
                ('conditioner', models.BooleanField()),
                ('cosmetic', models.BooleanField()),
                ('press', models.BooleanField()),
                ('pet', models.BooleanField()),
                ('bath', models.BooleanField()),
                ('business_lounge', models.BooleanField()),
                ('taxi', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rzd_app.vancharacter')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rzd_app.train')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('finished', models.BooleanField(default=False)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rzd_app.passenger')),
                ('seats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rzd_app.seat')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rzd_app.van'),
        ),
    ]
