# Generated by Django 3.2.22 on 2023-10-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='having_children',
            field=models.IntegerField(choices=[(1, 'Да'), (0, 'Нет')]),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='pets_attitude',
            field=models.IntegerField(choices=[(1, 'Положительно'), (0, 'Отрицательно')]),
        ),
    ]
