# Generated by Django 3.2.22 on 2023-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzd_app', '0002_auto_20231013_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
