# Generated by Django 3.2.22 on 2023-10-13 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rzd_app', '0003_alter_passenger_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='django_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
