# Generated by Django 3.2.22 on 2023-10-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzd_app', '0005_rename_django_user_id_passenger_django_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
