# Generated by Django 3.2.22 on 2023-10-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzd_app', '0006_alter_seat_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(null=True),
        ),
    ]
