# Generated by Django 3.2.22 on 2023-10-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rzd_app', '0007_alter_seat_seat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
    ]
