# Generated by Django 3.2.22 on 2023-10-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzd_app', '0008_remove_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='trip_with_animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='trip_with_child',
            field=models.IntegerField(choices=[(0, 'Еду один'), (1, 'Один ребенок'), (2, 'Двое детей'), (3, 'Трое детей'), (4, 'Четверо детей'), (5, 'Пятеро детей')], default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sociability',
            field=models.IntegerField(choices=[(1, 'Предпочитаю не общаться в поездке'), (2, 'Редко общаюсь'), (3, 'По-настроению'), (4, 'Часто общаюсь'), (5, 'Люблю заводить новые знакомства в поездах')]),
        ),
    ]
