# Generated by Django 3.2.22 on 2023-10-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rzd_app', '0009_auto_20231015_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='with_animals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='with_children',
            field=models.IntegerField(default=0),
        ),
    ]
